# Generated by Django 5.0.2 on 2024-03-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_category_ecoactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoactor',
            name='categories',
        ),
    ]
