# Generated by Django 5.0.2 on 2024-03-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_ecoactor_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcoActor',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nom',
            new_name='name',
        ),
    ]
