# Generated by Django 5.0.3 on 2024-03-23 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_ecoactor_rename_nom_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
