# Generated by Django 5.0.2 on 2024-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_role_alter_ecoactor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoactor',
            old_name='motdepasse',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
