# Generated by Django 5.0.3 on 2024-03-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_motdepasse_ecoactor_password_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoactor',
            old_name='activitis',
            new_name='activities',
        ),
        migrations.RenameField(
            model_name='ecoactor',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ecoactor',
            old_name='categories',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='ecoactor',
            old_name='ville',
            new_name='city',
        ),
    ]
