# Generated by Django 5.0.3 on 2024-03-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_activitis_ecoactor_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoactor',
            name='categorie',
        ),
    ]
