# Generated by Django 5.0.2 on 2024-04-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='member', max_length=100),
        ),
    ]
