# Generated by Django 5.0.2 on 2024-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoactor',
            name='trash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
