# Generated by Django 5.0.3 on 2024-03-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_ecoactor_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoactor',
            name='categories',
            field=models.ManyToManyField(to='myapp.category'),
        ),
    ]
