# Generated by Django 5.0.3 on 2024-03-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_ecoactor_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoactor',
            name='categorie',
            field=models.ManyToManyField(to='myapp.category'),
        ),
    ]
