# Generated by Django 5.0.3 on 2024-03-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ecoactor_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoactor',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='ecoactor',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
