# Generated by Django 5.0.3 on 2024-03-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ecoactor_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoactor',
            name='categories',
        ),
    ]
