# Generated by Django 5.0.2 on 2024-04-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_ecoactor_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoactor',
            name='trash',
            field=models.CharField(blank=True, choices=[('radioactive', 'Radioactive'), ('organic', 'Organic'), ('batteries', 'Batteries'), ('light bulbs', 'Light Bulbs'), ('biomedical', 'Biomedical'), ('paper', 'Paper'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('glass', 'Glass'), ('clothes', 'Clothes'), ('plastic', 'Plastic')], max_length=100, null=True),
        ),
    ]
