# Generated by Django 5.0.3 on 2024-03-28 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_ecoactor_categorie_alter_ecoactor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoactor',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='ecoactor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ecoactor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ecoactor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ecoactor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ecoactor',
            name='role',
        ),
    ]
