# Generated by Django 5.0.2 on 2024-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_prediction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoActorCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(default='actor', max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('activitis', models.CharField(max_length=255)),
                ('trash', models.CharField(blank=True, choices=[('radioactive', 'Radioactive'), ('organic', 'Organic'), ('batteries', 'Batteries'), ('light bulbs', 'Light Bulbs'), ('biomedical', 'Biomedical'), ('paper', 'Paper'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('glass', 'Glass'), ('clothes', 'Clothes'), ('plastic', 'Plastic')], max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='myapp.category')),
            ],
        ),
    ]
