# Generated by Django 5.0.3 on 2024-03-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_ecoactor_activities_remove_ecoactor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoactor',
            name='activities',
            field=models.CharField(default='Default activities', max_length=255),
        ),
        migrations.AddField(
            model_name='ecoactor',
            name='address',
            field=models.CharField(default='Default address', max_length=255),
        ),
        migrations.AddField(
            model_name='ecoactor',
            name='city',
            field=models.CharField(default='Default city', max_length=100),
        ),
        migrations.AddField(
            model_name='ecoactor',
            name='latitude',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='ecoactor',
            name='longitude',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='ecoactor',
            name='role',
            field=models.CharField(default='Default role', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecoactor',
            name='telephone',
            field=models.CharField(default='Default telephone', max_length=20),
        ),
    ]
