# Generated by Django 5.0.3 on 2024-03-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_ecoactor_activities_ecoactor_address_ecoactor_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoactor',
            name='category',
            field=models.CharField(default='Argiculture', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecoactor',
            name='role',
            field=models.CharField(default='Acteur ecologique', max_length=100),
        ),
    ]
