# Generated by Django 5.0.3 on 2024-03-28 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_ecoactor_category_alter_ecoactor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoactor',
            name='latitude',
            field=models.FloatField(default=5, max_length=20),
        ),
        migrations.AlterField(
            model_name='ecoactor',
            name='longitude',
            field=models.FloatField(default=5, max_length=20),
        ),
        migrations.AlterField(
            model_name='ecoactor',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecoactor',
            name='telephone',
            field=models.CharField(default='Default telephone', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be up to 8 digits.', regex='^\\d{1,8}$')]),
        ),
    ]
